name: publish JitPack
on:
  push:
    tags:
      - "v*"


jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

      - name: jitpack lookup and get
        run: |
          tag=$(git describe --tags --abbrev=0)
          
          response=$(curl -s "https://jitpack.io/api/builds/com/github/asasa868/DuskMVX/$tag")
          
          commit=$(echo $response | jq -r .commit)
          
          curl -s "https://jitpack.io/com/github/asasa868/DuskMVX/$commit/build.log" | grep "BUILD SUCCESS"