name: publish JitPack
on:
  push:
    tags:
      - "v*"


jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    #  - name: deploy file to server
    #   uses: ./  #这里要注意我们直接引用此repo下的action

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

      - name: jitpack lookup and get
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "tag: $tag"
          response=$(curl -s "https://jitpack.io/api/builds/com/github/asasa868/DuskMVX/$tag")
          echo "Response: $response"
          echo "Commit: $commit"
          
          commit=$(echo $response | jq -r .commit)
          
          curl -s "https://jitpack.io/com/github/asasa868/DuskMVX/$commit/build.log" | grep "BUILD SUCCESS"