name: publish JitPack
on:
  push:
    tags:
      - "*"


jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release with Release Notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Trigger JitPack lookup
        run: |
          echo "打包版本: ${{ github.repository }}&tag=${{ github.ref_name }}"
          curl -X GET "https://jitpack.io/api/builds/lookup?repo=github.com/${{ github.repository }}&tag=${{ github.ref_name }}"